version = 2

[globals]
"MAIN" = "main"

[files."slow"]
url = "http://127.0.0.1:8080/drifting.bin"
file = "drifting.bin"

[files."slower"]
url = "http://127.0.0.1:8080/slow.bin"
file = "slow.bin"

[files."test"]
url = "https://raw.githubusercontent.com/github/gitignore/{{$.MAIN}}/Go.gitignore"
file = "Go.gitignore"

[files."test".variables]
"VERSION" = "1.0.0"
