version = 1

[files."slow"]
url = "http://127.0.0.1:8080/drifting.bin"
file = "drifting.bin"

[files."test"]
url = "https://raw.githubusercontent.com/github/gitignore/main/Go.gitignore"
file = "Go.gitignore"
