package cli

import (
	"os"
	"strings"
	"testing"
)

// completionFlag is what every generated script appends to ask DAC what the next word could be.
const completionFlag = "--generate-shell-completion"

// TestCompletionWritesSuggestionsToStandardOutput is the regression test for a completion that installed cleanly and then did nothing at all.
// Help goes to standard error, because standard output carries the output contract.
func TestCompletionWritesSuggestionsToStandardOutput(t *testing.T) {
	// urfave finds the word being completed in os.Args when the root command is the one answering, rather than in the arguments it was handed, so a test driving Run has to supply it.
	original := os.Args
	os.Args = []string{"dac", completionFlag}
	t.Cleanup(func() { os.Args = original })

	result := run(t, []string{completionFlag})
	if result.status != ExitOK {
		t.Fatalf("completion exited %d: %s", result.status, result.stderr)
	}
	if !strings.Contains(result.stdout, "pull:") || !strings.Contains(result.stdout, "cache:") {
		t.Fatalf("command suggestions missing from stdout: %q", result.stdout)
	}
	if result.stderr != "" {
		t.Fatalf("completion wrote to stderr, where no shell reads it: %q", result.stderr)
	}
}

// TestCompletionScriptWritesToStandardOutput covers the other half of the same mistake, and the half that made it invisible.
// The script is sourced as `eval "$(dac completion bash)"`, which captures standard output.
func TestCompletionScriptWritesToStandardOutput(t *testing.T) {
	for _, shell := range []string{"bash", "zsh", "fish"} {
		result := run(t, []string{"completion", shell})
		if result.status != ExitOK {
			t.Fatalf("completion %s exited %d: %s", shell, result.status, result.stderr)
		}
		if !strings.Contains(result.stdout, "auto-generated by") {
			t.Fatalf("completion %s wrote no script to stdout: %q", shell, result.stdout)
		}
		if !strings.Contains(result.stdout, "dac") {
			t.Fatalf("completion %s script is not bound to dac: %q", shell, result.stdout)
		}
		if result.stderr != "" {
			t.Fatalf("completion %s wrote to stderr, where eval cannot see it: %q", shell, result.stderr)
		}
	}
}

// TestCompletionScriptSurvivesGlobalOptions covers the writer decision reading a command line it has to walk rather than index.
func TestCompletionScriptSurvivesGlobalOptions(t *testing.T) {
	paths := newProject(t)
	result := run(t, appendArgs(paths.base, "completion", "bash"))
	if result.status != ExitOK {
		t.Fatalf("completion exited %d: %s", result.status, result.stderr)
	}
	if !strings.Contains(result.stdout, "auto-generated by") {
		t.Fatalf("global options hid the completion script: %q / %q", result.stdout, result.stderr)
	}
}

// The reason Writer points at standard error in the first place is covered by TestHelpAndVersionStayOnStderr: standard output carries the output contract, and a command result is the only thing allowed onto it.

// TestCompletionSuggestsProjectCoordinates covers the argument that is worth completing.
func TestCompletionSuggestsProjectCoordinates(t *testing.T) {
	paths := newCompletableProject(t)
	for _, command := range []string{"path", "info", "remove", "unpack"} {
		result := run(t, appendArgs(paths.base, command, completionFlag))
		if result.status != ExitOK {
			t.Fatalf("%s completion exited %d: %s", command, result.status, result.stderr)
		}
		// The generated scripts split each line at its first colon: the coordinate is the word inserted, the URL is the description listed.
		want := []string{
			"app/geo@1.0.0:https://example.com/geo-1.bin\n",
			"app/geo@2.0.0:https://example.com/geo-2.bin\n",
			"tools/kit@3.0.0:https://example.com/kit.bin\n",
		}
		for _, line := range want {
			if !strings.Contains(result.stdout, line) {
				t.Fatalf("%s completion missing %q: %q", command, line, result.stdout)
			}
		}
	}
}

// TestCompletionStopsAfterOneCoordinate keeps a command that takes one asset from offering a second.
func TestCompletionStopsAfterOneCoordinate(t *testing.T) {
	paths := newCompletableProject(t)
	result := run(t, appendArgs(paths.base, "path", "app/geo@1.0.0", completionFlag))
	if result.status != ExitOK {
		t.Fatalf("completion exited %d: %s", result.status, result.stderr)
	}
	if result.stdout != "" {
		t.Fatalf("path suggested a second coordinate: %q", result.stdout)
	}
}

// TestCompletionOmitsCoordinatesAlreadyNamed covers the command that does take a list.
func TestCompletionOmitsCoordinatesAlreadyNamed(t *testing.T) {
	paths := newCompletableProject(t)
	for _, command := range [][]string{{"cache", "remove"}, {"unpack"}} {
		result := run(t, appendArgs(paths.base, append(command, "app/geo@1.0.0", completionFlag)...))
		if result.status != ExitOK {
			t.Fatalf("%v completion exited %d: %s", command, result.status, result.stderr)
		}
		if strings.Contains(result.stdout, "app/geo@1.0.0:") {
			t.Fatalf("%v re-suggested a named coordinate: %q", command, result.stdout)
		}
		for _, line := range []string{"app/geo@2.0.0:", "tools/kit@3.0.0:"} {
			if !strings.Contains(result.stdout, line) {
				t.Fatalf("%v missing %q: %q", command, line, result.stdout)
			}
		}
	}
}

// TestCompletionFallsBackToFlagsAfterADash covers the one case where the word under the cursor reaches DAC.
func TestCompletionFallsBackToFlagsAfterADash(t *testing.T) {
	paths := newCompletableProject(t)
	result := run(t, appendArgs(paths.base, "cache", "remove", "--", completionFlag))
	if result.status != ExitOK {
		t.Fatalf("completion exited %d: %s", result.status, result.stderr)
	}
	if !strings.Contains(result.stdout, "--force") {
		t.Fatalf("flag suggestions missing: %q", result.stdout)
	}
	if strings.Contains(result.stdout, "app/geo@") {
		t.Fatalf("coordinates offered where a flag was being typed: %q", result.stdout)
	}
}

// TestCompletionOutsideAProjectSaysNothing covers where completion actually runs.
func TestCompletionOutsideAProjectSaysNothing(t *testing.T) {
	paths := newProject(t)
	result := run(t, appendArgs(paths.base, "path", completionFlag))
	if result.status != ExitOK {
		t.Fatalf("completion exited %d: %s", result.status, result.stderr)
	}
	if result.stdout != "" || result.stderr != "" {
		t.Fatalf("completion without a manifest said something: %q / %q", result.stdout, result.stderr)
	}
}

// newCompletableProject writes a manifest holding two versions of one asset and a second asset, which is what makes a suggestion list worth reading.
// It builds the project through dac itself rather than by writing JSON, so the coordinates the shell is offered are the ones DAC would accept back.
func newCompletableProject(t *testing.T) projectFlags {
	t.Helper()
	paths := newProject(t)
	assertSuccess(t, runJSON(t, appendArgs(paths.base, "init")), "init")
	for _, asset := range [][2]string{
		{"app/geo@1.0.0", "https://example.com/geo-1.bin"},
		{"app/geo@2.0.0", "https://example.com/geo-2.bin"},
		{"tools/kit@3.0.0", "https://example.com/kit.bin"},
	} {
		result := runJSON(t, appendArgs(paths.base, "add", asset[0], asset[1], "--offline"))
		assertSuccess(t, result, "add")
	}
	return paths
}
